variable "namespace" {
  description = "Namespace, which could be your organization name or abbreviation, e.g. 'eg' or 'cp'"
  type        = string
  default     = ""
}

variable "environment" {
  description = "Environment, e.g. 'prod', 'staging', 'dev', 'pre-prod', 'UAT'"
  type        = string
  default     = ""
}

variable "tags" {
  description = "Additional tags (e.g. `map('BusinessUnit','XYZ')`"
  type        = map(string)
  default     = {}
}

variable "group_name_prefix" {
  description = "Prefix of IAM group name"
  type        = string
  default     = ""
}

variable "group_name_suffix" {
  description = "Suffix of IAM group name"
  type        = string
  default     = ""
}

variable "group_account_role" {
  description = "Map of group and role to be assumend in another account."
  type        = map(any)
  default     = {}

  # Expected value for the `group_account_role` is a map of then account name and assumed role.
  # The map key is the name of the account and the value is role arn to be assumed by the group.
  # For each account will be created group with assume role policy.
  #
  # Example:
  #
  # group_role = {
  #   "prod" = "arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME"
  # }
  #
  # Creates:
  #   - group named ${namespace}-${environment}-${group_name_prefix}-${account}-${group_name_suffix}
  #   - policy with assumable role where resource will be arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME
  #   - group policy attachment

}

variable "assumable_role_create" {
  description = "Whether to create a role in the caller account "
  type        = bool
  default     = true
}

variable "assumable_role_name" {
  description = "IAM role name. Defaults to auto generated role name"
  type        = string
  default     = ""
}

variable "assumable_role_name_generated" {
  description = "Whether to create a role with assumable_role_name or autogenerated"
  type        = bool
  default     = false
}

variable "assumable_role_path" {
  description = "IAM role path"
  type        = string
  default     = "/"
}

variable "assumable_role_mfa" {
  description = "Whether role requires MFA"
  type        = bool
  default     = true
}

variable "assumable_role_permissions_boundary_arn" {
  description = "Permissions boundary ARN to use for IAM role"
  type        = string
}

variable "assumable_role_trusted_arns" {
  description = "ARNs of AWS entities who can assume these roles"
  type        = list(string)
  default     = []
}

variable "assumable_role_services" {
  description = "AWS Services that can assume these roles	"
  type        = list(string)
  default     = []
}

variable "assumable_role_attach_admin_policy" {
  description = "Whether to attach an admin policy to a role"
  type        = bool
  default     = false
}

variable "assumable_admin_role_policy_arn" {
  description = "Policy ARN to use for admin role"
  type        = string
  default     = "arn:aws:iam::aws:policy/AdministratorAccess"
}

variable "assumable_additional_role_policy_arns" {
  description = "List of ARNs of IAM policies to attach to IAM role"
  type        = list(string)
  default     = []
}

variable "assumable_tags" {
  description = "A map of tags to add to IAM role resources"
  type        = map(string)
  default     = {}
}
